import os

#Dependencias Widnows
print("Instalando Dependencias Windows...")
print("")
os.system("pip3.8 install pyqt5")
os.system("pip3.8 install pyqtwebengine")
os.system("pip3.8 install pyahocorasick")
os.system("pip3.8 install pywin32")
os.system("pip3.8 install Pillow")
os.system("pip3.8 install pdfminer.six")
os.system("pip3.8 install unidecode")
os.system("pip3.8 install natsort")
print("")
print("Dependecias Windows Instaladas")
print("")

print("Preparando para Instalar Dependencias VM")
print("")
print("ATENCAO: ESSE PROCESSO PODE DEMORAR. NAO DESLIGUE SEU COMPUTADOR OU REMOVA SUA CONEXÃO COM A INTERNET.")
print("É recomendado fechar todos os outros programas enquanto esse processo é executado")
print("")
#Dependecias maquina virtual
print("Senha Máquina Virtual para Update")
print("")
os.system("ubuntu1804 run sudo apt-get update")
print("")
print("Senha Máquina Virtual para Modificar Alias")
print("")
os.system("ubuntu1804 run sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 10")
print("")
print("Senha Máquina Virtual para Instalar Pacotes")
print("")
os.system("ubuntu1804 run sudo apt-get install xserver-xephyr libxrandr-dev ffmpeg python3-pip openjdk-8-jdk python3-hunspell libhunspell-dev unoconv")
print("")
print("Instalação via Pip")
print("")
os.system("ubuntu1804 run pip3 install Cython")
os.system("ubuntu1804 run pip3 install vlibras-translate")
print("")
print("Setup translate...")
print("")
os.system("ubuntu1804 run python vl_setup.py")
print("")
print("Instalação Concluída!")
print("")
print("Execute 'python3.8 MDLib.py' para iniciar o sistema.")
